EMOJI_WARN_EMBEDS_PATH = r"data/embeds/automod/emoji_warn_embeds.json"
MENTION_WARN_EMBEDS_PATH = r"data/embeds/automod/mention_warn_embeds.json"
SIMILARITY_WARN_EMBEDS_PATH = r"data/embeds/automod/similarity_warn_embeds.json"
SWEAR_WARN_EMBEDS_PATH = r"data/embeds/automod/swear_warn_embeds.json"
UPPERCASE_WARN_EMBEDS_PATH = r"data/embeds/automod/uppercase_warn_embeds.json"
URL_WARN_EMBEDS_PATH = r"data/embeds/automod/url_warn_embeds.json"
